version: "3"

services:
  web:
    image: python:3.8-alpine
    container_name: wagtail_web
    ports:
      - "80:8000"
    volumes:
      - ./wagtail.sh:/app/wagtail.sh
      - ./data:/app/blog
    working_dir: /app
    command: ["/bin/sh", "-c", "chmod +x /app/wagtail.sh && /app/wagtail.sh"]
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=psw
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DATABASE_URL=postgres://wagtail:wagtail@db:5432/wagtaildb
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: wagtail_db
    restart: always
    environment:
      POSTGRES_USER: wagtail
      POSTGRES_PASSWORD: wagtail
      POSTGRES_DB: wagtaildb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
